# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - cd cmd/protoc-gen-graphql && go mod tidy

builds:
  - id: "protoc-gen-graphql"
    main: ./cmd/protoc-gen-graphql
    binary: protoc-gen-graphql
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: protoc-gen-graphql
    builds:
      - protoc-gen-graphql
    format: tar.gz
    name_template: >-
      protoc-gen-graphql_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

  - id: nebucloud-gateway
    format: tar.gz
    files:
      - src: ./ptypes
        dst: ./ptypes
      - src: ./runtime
        dst: ./runtime
      - src: ./spec
        dst: ./spec
      - README*
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: nebucloud
    name: nebucloud-gateway

hooks:
  pre:
    - cd cmd/protoc-gen-graphql && go mod edit -dropreplace github.com/nebucloud/nebucloud-gateway
  post:
    - cd cmd/protoc-gen-graphql && go mod edit -replace github.com/nebucloud/nebucloud-gateway=../..